project:
  type: website
  output-dir: docs
  
website:
  title: "Data Visualizations"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Visualizations"
        menu:
          - text: "Redesign 1"
            href: redesign1.qmd
          - text: "Redesign 2"
            href: redesign2.qmd
          - text: "Redesign 3"
            href: redesign3.qmd
      - text: "Oil Production"
        menu:
          - text: "Bar Plot"
            href: oil_bar.qmd
          #- text: "Geospatial"
          # href: oil_map.qmd
          
format:
  html:
   css: styles.css

